README.md
=> Revert "Fix link @Filou64"

src/GameWindow.cpp, src/GameWindow.h, src/Managers/ConfigManager.cpp, src/ScreenStages/GameScreen.cpp, src/ScreenStages/GameScreen.h, src/ScreenStages/MainScreen.cpp, src/ScreenStages/MainScreen.h, src/Wisp/WispWindow.h
This commit was lost during the fork work.
=> Reimport contribution from Johnny fixing windowing resize issue.

src/CrossApp.cpp, src/CrossPCH.h, src/CrossUO.cpp, src/GameWindow.cpp, src/GameWindow.h, src/Globals.cpp, src/Globals.h, src/Gumps/GumpOptions.cpp, src/Gumps/GumpOptions.h, src/Gumps/GumpScreenServer.cpp, src/Managers/ConfigManager.cpp, src/Managers/ConfigManager.h, src/ScreenStages/GameScreen.cpp, src/ScreenStages/GameScreen.h, src/ScreenStages/MainScreen.cpp, src/ScreenStages/MainScreen.h, src/ServerList.cpp, src/Sockets.cpp, src/Sockets.h, src/Utility/PingThread.cpp, src/Utility/PingThread.h, src/Wisp/WispWindow.h
Disable ping feature permanently until a workaround is found or we decide to remove completely.
=> Fix windowing resize issue

src/CrossUO.cpp
=> add missing present gift Gump id 

src/Managers/ClilocManager.cpp, src/Managers/ClilocManager.h, src/Managers/PacketManager.cpp, src/Managers/PacketManager.h
Fix for issues #37 
Before :
After:
=> Fix XmfHtml Gump element to phase args issues #37

src/Gumps/GumpSecureTrading.cpp
=> add support for new gui secure trade

src/ScreenStages/GameScreen.cpp, src/TextEngine/GameConsole.cpp
fix for issues #55 
Now ctrl+q work like Original Client clean up old code
=> Fix ctrl+q parity remove old not working code.

src/GameWindow.cpp
Fix for paste issues #54 
one thing we need to find a way to bind the ctrlkey to the cmd key on OSX
=> Fix for paste.

external/loguru.h, src/CommonInterfaces.cpp, src/Constants.h, src/GameObjects/GameCharacter.cpp, src/GameObjects/GameCharacter.h, src/Gumps/GumpOptions.cpp, src/Gumps/GumpPaperdoll.cpp, src/Gumps/GumpSecureTrading.cpp, src/Gumps/GumpSecureTrading.h, src/Gumps/GumpSelectFont.cpp, src/Gumps/GumpStatusbar.cpp, src/Managers/ConfigManager.cpp, src/Managers/ConfigManager.h, src/Managers/MacroManager.cpp, src/Managers/PacketManager.cpp, src/Network/Packets.cpp, src/ScreenStages/GameScreen.cpp, src/Walker/PathFinder.cpp, src/api/enumlist.h
- Add Gender Enum
- Add Direction Enum
- Simplify WalkData into Steps
- Add option to automatically open doors
- Reenable boat movement
- Disable loguru assets due to packet printing bad characters
- Enforce some types
=> Lots of minor things and cleanups

src/Gumps/GumpSecureTrading.cpp, src/Gumps/GumpSecureTrading.h
=> Small fix for items box new trade gump

src/GameObjects/GameObject.cpp, src/Gumps/GumpOptions.cpp, src/Managers/ConfigManager.cpp, src/Managers/ConfigManager.h
for issues #4 
Original Client
CrossUO:
=> Object handlers fix corpse

src/Globals.cpp, src/Globals.h, src/Gumps/GumpScreenSelectProfession.cpp, src/Gumps/GumpScreenSelectProfession.h, src/Managers/PacketManager.cpp
For issues #53  
Initial work on expansion control in Character creation
=> Character Creation Expansion control

src/CrossUO.cpp, src/GameObjects/GameCharacter.cpp, src/Gumps/GumpOptions.cpp, src/Managers/ConfigManager.cpp, src/Managers/ConfigManager.h, src/ScreenStages/GameScreen.cpp
=> Add option to AlwaysDisplayHumanoidsName

.travis.yml, travis.sh
Travis nightly build OSX and Unbuntu
=> Nightly travis

external/ass.h, external/popts.h, src/GameObjects/GameItem.cpp, src/Gumps/Gump.cpp, src/Gumps/GumpCustomHouse.cpp, src/Gumps/GumpPaperdoll.cpp, src/Gumps/GumpScreenSelectTown.cpp, src/Gumps/GumpScreenServer.cpp, src/Gumps/GumpSkills.cpp, src/Managers/FontsManager.cpp, src/Managers/GumpManager.cpp, src/Managers/IntlocManager.cpp, src/Managers/MapManager.cpp, src/Managers/PacketManager.cpp, src/Managers/UOFileReader.cpp, src/Platform.h, src/ServerList.cpp, src/ServerList.h
Try to fix shadowing instances by reproducing shadow result (as to void
breaking stuff)
=> Reenable shadowing warning

src/CrossUO.cpp, src/api/config.h, src/api/file.cpp, src/api/uodata.cpp, src/api/uodata.h, src/tools/xuodump.cpp
A bit better api config for logging.
Simplify and protect some code in uodata.
=> Implement a minimal xuodump application for testing purposes.

common/fs.h, common/log.h, common/str.h, external/loguru.h, external/lookup3.h, src/Logging.cpp, tools/xuodump/xuodump.cpp, tools/xuoi/main.cpp
xuoi is now able to download all uo artifacts directly from mythic servers.
repacking is under the way, once finished users will not need to download uo data files using wine anymore.
=> xuoi downloader working

tools/xuoi/main.cpp
xuoi can mirror official uo patch server by downloading all individual
artifacts for each listed product, placing them in a structured
directory listing to use with a custom server implementation to serve
actual data to the official patcher. I've tested a full official install
with a mirrored server and works perfectly.
The mirror mode also supports incremental mirroring, where following
updates will download only needed files, with this we can go back in
time on ultima versions to reproduce any client at any moment in time.
This is really useful for tracking client changes, debugging and
reversing new changes.
=> xuoi - mirror official uo patch server mode

src/Platform.h, src/ScreenStages/GameScreen.cpp
-PostMessage and SendMessage dont
reach sld event loop INPUTTEXT or
KEY_DOWN
=> Add support to VK_RETURN (SLDK_CLEAR)

.travis.yml, appveyor.yml, tools/xuoi/accounts.cpp, tools/xuoi/http.cpp, tools/xuoi/shards.cpp, travis.sh
- http follow redirects because github releases are aliases
- minor tweak on accounts view
- nightly deploying fixes and include xuolauncher
=> Download latest shard listing

src/CrossUO.cpp
=> Enable in game World map

src/ScreenStages/GameScreen.cpp
-you can edit the text without moving character.
=> Don't move character if text in the console

common/str.h, tools/xuodump/xuodump.cpp, tools/xuoi/CMakeLists.txt, tools/xuoi/accounts.cpp, tools/xuoi/http.cpp, tools/xuoi/main.cpp, tools/xuoi/shards.cpp, xuocore/CMakeLists.txt, xuocore/enumlist.h, xuocore/mappedfile.h, xuocore/uodata.cpp, xuocore/uodata.h, xuocore/uolib.h, xuocore/uop.cpp, xuocore/uop.h
- remove some string headers
- add initial uop helper functions to map hash to filenames and ids
=> xuoi patch diff helper

src/GUI/GUIChecktrans.cpp, src/Gumps/Gump.cpp, src/Gumps/Gump.h
=> fix for guichecktrans on page 0 cleanup

src/Managers/PluginManager.cpp
-TODO: cleanup duplicated code & event system
=> Coment code that send packet twice in PluginSendFunction

common/str.h, src/CMakeLists.txt, src/CrossUO.cpp, src/Gumps/GumpSpell.cpp, src/Gumps/GumpSpell.h, src/Gumps/GumpSpellbook.cpp, src/Gumps/GumpSpellbook.h, src/Managers/FontsManager.cpp, src/Managers/GumpManager.cpp, src/Managers/MacroManager.cpp, src/Network/PluginPackets.cpp, src/Renderer/RenderState.cpp, src/Spells.cpp, src/Spells.h, xuocore/enumlist.h
Refactor code by expanding spells and spellbooks templates
to reduce exceptional cases from gump building.
Overall visual fixes on most books.
=> client: Mastery Spellbook minor fixes

src/Gumps/GumpMinimap.cpp, src/Managers/MapManager.cpp, xuocore/mulstruct.h
Slight merge collision between this and master as it already pulled changes from pending pull request for xuocore/mulstruct.h
=> Add Hue info to RADAR_MAP_CELLS so GumpMinimap:GenerateMap can show Hue

src/CrossUO.cpp, src/Globals.cpp, src/Gumps/GumpSpell.cpp, src/Gumps/GumpSpell.h, src/Gumps/GumpSpellbook.cpp, src/Managers/ClilocManager.cpp, src/Managers/ClilocManager.h, src/Managers/IntlocManager.cpp, src/Managers/IntlocManager.h, src/Managers/ProfessionManager.cpp, src/Managers/SpeechManager.cpp, src/Platform.cpp, src/Spells.cpp, src/ToolTip.cpp, src/ToolTip.h
a bit of cliloc string optimizations and cleanup
=> client: fix spellbook spell link to correct pages

src/Gumps/GumpScreenGame.cpp, src/Weather.cpp, src/Weather.h
- Fix weather effect which don't follow window movement
- Add/remove weather particles based on windows size
=> Fix weather issues on screen drag, add effects based on screen size

src/Managers/PacketManager.cpp, src/ScreenStages/GameScreen.cpp, src/ScreenStages/GameScreen.h, src/Weather.cpp, src/Weather.h
- Add earthquake to weather packet
- for future use with spell earthquake
=> Add Earthquake to Weather

src/CrossUO.cpp, src/Gumps/GumpOptions.cpp, src/Managers/ConfigManager.cpp, src/Managers/ConfigManager.h, src/Managers/PacketManager.cpp, xuocore/enumlist.h
- Add large gumps id to container.txt
- Options to enable large gumps display in miscellaneous
=> Add Large Gumps

src/GameObjects/GameCharacter.cpp, src/GameObjects/GameCharacter.h, src/Managers/AnimationManager.cpp, src/Managers/MouseManager.cpp, src/Network/Packets.cpp, src/Network/Packets.h
=> Add boat pilot mouse control packet

src/TextEngine/GameConsole.cpp
-calcul new position console text cursor fix left and right arrow
=> Console fix

src/Config.cpp, src/Main.cpp
- add a hopefully more detailed logging
- only force data validation if client version is unset
=> client: improve client version compatibility validation
